blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.ListView.as_view(), name='postslist'),
    path('<slug:slug>/', views.DetailView.as_view(), name='detail'),
]

core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
]

km/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('blog/', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.utils import timezone

class CommonInfo(models.Model):
    'Абстрактная модель для общих полей'
    title = models.CharField(max_length=200, verbose_name='Заголовок')
    description = models.CharField(max_length=160, blank=True, null=True, verbose_name='Краткое описание')
    to_publish = models.BooleanField(verbose_name='Опубликовать', default=True)

    class Meta:
        abstract = True

class Rubric(CommonInfo):

    class Meta:
        verbose_name = 'Рубрика'
        verbose_name_plural = 'Рубрики'

    def __str__(self):
        return self.title


class Post(CommonInfo):
    rubric = models.ForeignKey(Rubric, on_delete=models.CASCADE, verbose_name="Рубрика")
    slug = models.CharField(max_length=200, unique=True, verbose_name='url статьи')    
    text = models.TextField(blank=True, null=True, verbose_name='Текст')
    keywords = models.CharField(max_length=255, blank=True, null=True, verbose_name='Ключевые слова')
    create_date = models.DateTimeField(default=timezone.now, verbose_name='Дата создания')
    published_date = models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE, verbose_name='Автор')

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

    def __str__(self):
        return self.title

core/models.py
from django.db import models

import pdb

class CommonInfo(models.Model):
    'Абстрактная модель для общих полей'
    title = models.CharField(max_length=50, verbose_name='Заголовок')
    to_publish = models.BooleanField(verbose_name='Опубликовать', default=True)

    class Meta:
        abstract = True

class CoreData(CommonInfo):
    mainMenu = (
        ("main", "Главное"),
        ("mebel", "Мебель"),
        ("materials", "Материалы"),
        ("blog", "Блог"),
        ("about", "О себе"))
    to_menu = models.CharField(max_length=10, choices=mainMenu, verbose_name='Прицепить к меню', blank=True, null=True)
    text = models.TextField(verbose_name='Текст')    
    usort = models.PositiveSmallIntegerField(verbose_name='Сортировка', default=1)

    class Meta:
        verbose_name = 'Данные сайта'
        verbose_name_plural = 'Данные сайта'
    
    def __str__(self):
        return self.title

class Contacts(models.Model):
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    country = models.CharField(max_length=100, verbose_name='Страна', blank=True)
    city = models.CharField(max_length=50, verbose_name='Город', blank=True)
    street = models.CharField(max_length=100, verbose_name='Улица', blank=True)
    home = models.CharField(max_length=10, verbose_name='Дом', blank=True)
    ofice = models.CharField(max_length=10, verbose_name='Офис', blank=True)
    phone_1 = models.CharField(max_length=20, verbose_name='Телефон 1', blank=True)
    phone_2 = models.CharField(max_length=20, verbose_name='Телефон 2', blank=True)
    mail = models.EmailField(max_length=254, verbose_name='email', blank=True)
    # soc = 

    class Meta:
        verbose_name = 'Контакты'
        verbose_name_plural = 'Контакты'

    def __str__(self):
        return self.title

class SocNet(models.Model):
    pass

blog/views.py
from django.shortcuts import render
from django.views import generic
from .models import Post

import pdb


class ListView(generic.ListView):
    model = Post
    template_name = 'blog/blog_list.html'
    context_object_name = 'posts_list'
    # pdb.set_trace()

    def get_queryset(self):
        return Post.objects.order_by('-published_date')

class DetailView(generic.DetailView):
    model = Post
    template_name = 'blog/blog_detail.html'
    context_object_name = 'post_detail'
    # pdb.set_trace()

    def get_queryset(self):
        return Post.objects

core/views.py
from django.shortcuts import render
from django.views import generic
from . import models

import pdb


class IndexView(generic.ListView):
    template_name = 'core/index.html'
    context_object_name = 'coredata_text'
    # pdb.set_trace()

    def get_queryset(self):
        return models.CoreData.objects.filter(to_publish=True, to_menu="main").order_by('usort')

# def index(init):
#     pdb.set_trace()
    
#     text = models.CoreData.objects.filter(to_publish=True, on_main=True).order_by('usort')
#     contex_var = {'text': text}
    
#     return render(request, template_name, contex_var)

blog/templates/blog/blog_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% block description %}{{ post_detail.description }}{% endblock %}
{% block keywords %}{{ post_detail.keywords }}{% endblock %}
{% block title %}{{ post_detail.title }}{% endblock %}

{% block content %}
<article  class="content-list-item">
  <header class="header_post_list">
    <a href="">Рубрика: {{ post_detail.rubric }}. | </a><span>Дата публикации: {{ post_detail.published_date }}</span>
  </header>
  <h1>{{ post_detail.title }}</h1>    
  {{ post_detail.text | safe }}
<footer class="footer-post">
  <span>Поделиться: </span>
  <ul class="post-share-buttons">
    <li><a class="icon-vkontakte-1" href="https://vk.com/share.php?url={{ request.get_host }}{{ request.get_full_path }}" onclick="window.open(this.href, 'Опубликовать ссылку во Вконтакте', 'width=700,height=500,toolbar=0,status=0'); return false"></a></li>
    <li><a class="icon-odnoklassniki-square" href="https://connect.ok.ru/offer?url={{ request.get_host }}{{ request.get_full_path }}" onclick="window.open(this.href, 'Опубликовать ссылку в Одноклассниках', 'width=700,height=500,toolbar=0,status=0'); return false"></a></li>
    <li><a class="icon-at" href="http://connect.mail.ru/share?url={{ request.get_host }}{{ request.get_full_path }}" onclick="window.open(this.href, 'Опубликовать ссылку на Mail.ru', 'width=700,height=500,toolbar=0,status=0'); return false"></a></li>
    <li><a class="icon-facebook-official" href="https://www.facebook.com/sharer/sharer.php?u={{ request.get_host }}{{ request.get_full_path }}" onclick="window.open(this.href, 'Опубликовать ссылку в FaceBook', 'width=700,height=500,toolbar=0,status=0'); return false"></a></li>
  </ul>
</footer>
</article>
{% endblock %}


blog/templates/blog/blog_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% block keywords %}статьи, мебель{% endblock %}
{% block title %}Полезные статьи про мебель{% endblock %}

{% block content %}

{% if posts_list %}
<ul class="content-list">
  {% for post in posts_list %}
  <li class="content-list-item">
    <article>
      <header class="header_post_list"><a href="">Рубрика: {{ post.rubric }}. | </a>
        <span>Дата публикации: {{ post.published_date }}</span></header>
      <h2><a class="post_title" href="{% url 'blog:detail' post.slug %}">{{ post.title }}</a></h2>
      <div>{{ post.text | safe | truncatewords_html:100 }}</div>
      <a href="{% url 'blog:detail' post.slug %}" class="post_read_more">Читать дальше</a>
    </article>
  </li>
  {% endfor %}
</ul>
{% else %}
  <p>No polls are available.</p>
{% endif %}


{% endblock %}


core/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <!--[if lt IE 9]> 
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script> 
    <![endif]-->
    <link rel="icon" type="image/x-icon" href="{% static 'core/favicon.png' %}">
    <link rel="stylesheet" href="{% static 'core/css/corefonts.css' %}" />
    <link rel="stylesheet" href="{% static 'core/css/core.css' %}" />
    <link rel="stylesheet" href="{% static 'core/css/fontello.css' %}" />
    <link rel="stylesheet" href="{% static 'blog/css/blog.css' %}" />
    <meta charset="utf-8">
    <meta name="description" content="{% block description %}Шкафы-купе, гардеробные и кухни на заказ в Белгороде.{% endblock %}">
    <meta name="keywords" content="{% block keywords %}шкафы-купе, гардеробные, кухни, прихожие, шкафы{% endblock %}">
    <title>{% block title %}К-МЕБЕЛЬ{% endblock %}</title>
</head>

<body>
    
{% block header %}
{% include 'core/header.html' %}
{% endblock %}
<main class="g-container" role="main">
{% block content %}
{% include template_content %}
{% endblock %}
</main>
 <footer class="footer-main"></footer>   
</body>
</html>

core/templates/core/header.html
<header class="header-main">
  <div class="g-container flex-row">
    <nav id="globalnav" class="flex-row">
      <ul class="gn-list flex-row">
        <li><a class="logo" href="/" 
            title="shkafkupebel.ru - Домашняя страница" rel="home"></a></li>
        <li><a href="/" title="Главная">Главная</a></li>
        <li><a href="#" title="Мебель">Мебель</a></li>
        <li><a href="#" title="Материалы">Материалы</a></li>
        <li><a href="/blog/" title="Блог">Блог</a></li>
        <li><a href="#" title="О себе">О себе</a></li>
        <li><a href="#" title="Контакты"><span class="icon-phone-squared"></span>
            <span class="icon-mail-alt"></span></a></li>
      </ul>
    </nav>
  </div>  
</header>
<div style="width: 100%; height: 70px;"><span></span></div>

core/templates/core/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}К-МЕБЕЛЬ|Главная{% endblock %}

{% block content %}
 <h1 class="main_title">Шкафы-купе . Гардеробные . Шкафы платяные</h1>
 <h2 class="main_title">на заказ в Белгороде</h2>
<div class="sticker_block flex-row">
  <div id="stic_1" class="sticker">
    <div class="stick_img_wrap">
      <img src="{% static 'core/images/dsgn/operator.svg' %}" alt="оператор">
    </div><span></span>      
    <p>Мы работаем онлайн Задать вопрос</p>
  </div>
  <div id="stic_2" class="sticker">
    <div class="stick_img_wrap">
      <img src="{% static 'core/images/dsgn/shkaf.svg' %}" alt="шкаф">
    </div><span></span>
    <p>Получить дизайн проект бесплатно</p>
  </div>
  <div id="stic_3" class="sticker">
    <div class="stick_img_wrap">
      <img src="{% static 'core/images/dsgn/saw.svg' %}" alt="пила">
    </div><span></span>
    <p>Преимущества нашего производства</p>
  </div>
</div>
<div style="text-align: center;">
    <button class="bt_order" name="b_order" value="1" type="submit">сделать заказ</button>
</div>

{% for data in coredata_text %}
{{ data.text | safe }}
{% endfor %}

<div class="howwork flex-column">
  <h2>Как мы работаем</h2>
  <div class="flex-row">
    <figure>
      <img src="{% static 'core/images/dsgn/hw1.svg' %}" alt="">
      <figcaption>обсуждаем предварительный проект и считаем стоимость</figcaption>
    </figure>
    <figure>
      <img src="{% static 'core/images/dsgn/hw2.svg' %}" alt="">
      <figcaption>выезжаем на замер</figcaption>
    </figure>
    <figure>
      <img src="{% static 'core/images/dsgn/hw3.svg' %}" alt="">
      <figcaption>корректируем проект и делаем окончательный расчёт стоимости</figcaption>
    </figure>
    <figure>
      <img src="{% static 'core/images/dsgn/hw4.svg' %}" alt="">
      <figcaption>заключаем договор</figcaption>
    </figure>
    <figure>
      <img src="{% static 'core/images/dsgn/hw5.svg' %}" alt="">
      <figcaption>изготавливаем, привозим и собираем</figcaption>
    </figure>
  </div>
</div>

{% endblock %}